services:
  db:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

  sveltekit:
    build:
      context: ./sveltekit-app
      dockerfile: Dockerfile.dev
    volumes:
      - ./sveltekit-app:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    env_file:
      - ./sveltekit-app/.env
    command: [ "npm", "run", "dev", "--", "--host" ] # So Vite listens on 0.0.0.0
    depends_on:
      - db
    networks:
      - app-network

volumes:
  mariadb_data:

networks:
  app-network: